---

name: Packer

on:
  push:

jobs:
  packer:
    runs-on: ubuntu-18.04
    name: packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # fix backwards incompatibilities in template
      - name: Fix Template
        uses: gomex/packer-github-actions@master
        with:
          command: fix
          target: packer.json

      # validate templates
      - name: Validate Template
        uses: gomex/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: packer.json

      # build artifact
      - name: Build Artifact
        uses: gomex/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort"
          target: packer.json
        env:
          PACKER_LOG: 1
          DO_API_TOKEN: ${{ secrets.DO_API_TOKEN }}

